[theme]
# TrueContext Dark Theme
primaryColor = "#00A4E4"  # TrueContext Blue (kept for accents)
backgroundColor = "#0E1117"  # Dark background
secondaryBackgroundColor = "#262730"  # Dark secondary
textColor = "#FAFAFA"  # Light text for contrast
font = "sans serif"

[server]
maxUploadSize = 50
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false